# Generated by Django 4.2.23 on 2025-12-29 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_attendance_overtime_and_more'),
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndertimeLeaveDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('deduction_date', models.DateField(verbose_name='Deduction Date')),
                ('undertime_minutes', models.FloatField(help_text='Total undertime in minutes', verbose_name='Undertime (Minutes)')),
                ('credits_deducted', models.FloatField(help_text='Leave credits deducted (formula: minutes ÷ 480)', verbose_name='Credits Deducted')),
                ('balance_before', models.FloatField(default=0, help_text='Leave balance before deduction', verbose_name='Balance Before')),
                ('balance_after', models.FloatField(default=0, help_text='Leave balance after deduction', verbose_name='Balance After')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('attendance_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendance', verbose_name='Related Attendance')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undertime_deductions', to='employee.employee', verbose_name='Employee')),
                ('leave_type_id', models.ForeignKey(help_text='The leave type from which credits were deducted', on_delete=django.db.models.deletion.PROTECT, to='leave.leavetype', verbose_name='Leave Type')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deductions', to='employee.employee', verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Undertime Leave Deduction',
                'verbose_name_plural': 'Undertime Leave Deductions',
                'ordering': ['-deduction_date', '-created_at'],
            },
        ),
    ]
